spring:
  datasource:
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: whitney@akred.com
    password: YOUR_GMAIL_APP_PASSWORD
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    team.projectpulse: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG
